[package]
name = "smdton"
version = "0.1.0"
edition = "2021"
authors = ["smwasm@outlook.com"]
repository = "https://github.com/smwasm/smdton.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
lazy_static = "1.4.0"

[lib]
crate-type = ["rlib", "cdylib"]
